# -*- coding: utf-8 -*-
"""
Setup wizard for the Antigravity plugins suite (no-admin, per-user install).

The payload is the PyInstaller onedir build of aglaunch.py plus a portable node.exe,
so after this runs the user needs neither Node.js nor Python installed - which was the
single biggest source of "it works on my machine" failures for this project.
"""
import os
import shutil
import subprocess
import sys
import threading
import queue
from pathlib import Path

PRODUCT = "Antigravity 插件增强套件"
VERSION = "1.1.0"
DIR_NAME = "AntigravityPlugins"
BATCH_HEAD = (
    "@echo off\r\n"
    "rem generated by AntigravityPlugins-Setup - keep this file ASCII-only:\r\n"
    "rem cmd.exe desyncs its own batch read offset when chcp changes the codepage mid-file.\r\n"
    'set "EXE=%~dp0bin\\AntigravityPlugins.exe"\r\n'
    "if not exist \"%EXE%\" (\r\n"
    "    echo [ERROR] AntigravityPlugins.exe not found next to this script.\r\n"
    "    pause\r\n"
    "    exit /b 1\r\n"
    ")\r\n"
)
LAUNCHERS = [
    ("一键全量部署.bat", "--deploy", True),
    ("恢复官方原版.bat", "--restore", True),
    ("启动插件管理中心.bat", "--gui", True),
]


def default_target():
    lapp = os.environ.get("LOCALAPPDATA") or str(Path.home() / "AppData" / "Local")
    return Path(lapp) / DIR_NAME


def bundle_root():
    """Where the bundled `tree/` and `runtime/` live.

    Normally PyInstaller's _MEIPASS of the Setup build. AG_SETUP_BUNDLE exists so the
    installer logic can be exercised against an already-built tree without repacking
    the 59 MB wrapper (the variable must point at a folder containing tree/ + runtime/).
    """
    return Path(os.environ.get("AG_SETUP_BUNDLE") or getattr(sys, "_MEIPASS",
                                                             str(Path(__file__).resolve().parent)))


def copy_tree(src, dst, report=None):
    import shutil
    dst.mkdir(parents=True, exist_ok=True)
    files = [p for p in src.rglob("*") if p.is_file()]
    total = len(files)
    for i, p in enumerate(files, 1):
        rel = p.relative_to(src)
        out = dst / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(str(p), str(out))
        if report and (i % 40 == 0 or i == total):
            report(i * 100 // total)
    return total


def write_launchers(target):
    """ASCII-only .bat entry points that call the bundled exe (no Python needed)."""
    for name, args, _pause in LAUNCHERS:
        body = BATCH_HEAD + "%EXE% " + args + "\r\n" + "if errorlevel 1 pause\r\n"
        (target / name).write_bytes(body.encode("ascii"))


def install_guard_autostart(target, enable=True):
    startup = Path(os.environ.get("APPDATA", str(Path.home()))) / "Microsoft" / "Windows" \
        / "Start Menu" / "Programs" / "Startup"
    vbs = startup / "AntigravityPluginGuard.vbs"
    if not startup.exists():
        return False
    if not enable:
        if vbs.exists():
            try:
                vbs.unlink()
            except Exception:
                pass
        return False
    exe = str(target / "bin" / "AntigravityPlugins.exe")
    body = (
        "' generated by AntigravityPlugins-Setup - ASCII only, CRLF\r\n"
        "' silent auto-repatch daemon, 15s after logon, no window\r\n"
        "Set fso = CreateObject(\"Scripting.FileSystemObject\")\r\n"
        "Set shell = CreateObject(\"WScript.Shell\")\r\n"
        "Dim exe\r\n"
        "exe = \"%s\"\r\n"
        "If fso.FileExists(exe) Then\r\n"
        "    WScript.Sleep 15000\r\n"
        "    shell.Run Chr(34) & exe & Chr(34) & \" --guard\", 0, False\r\n"
        "End If\r\n" % exe
    )
    vbs.write_bytes(body.encode("ascii"))
    return True


class Worker:
    """Runs the install steps off the GUI thread and reports progress."""

    def __init__(self, target, desktop_shortcuts, autostart, deploy_now, out):
        self.target = Path(target)
        self.desktop = desktop_shortcuts
        self.autostart = autostart
        self.deploy_now = deploy_now
        self.out = out
        self.failed = False

    def say(self, line):
        self.out.put(("log", line))

    def pct(self, value, label=""):
        self.out.put(("pct", (value, label)))

    def run(self):
        try:
            self.step_install()
        except BaseException as e:
            import traceback
            self.say("[致命错误] %s" % e)
            self.say(traceback.format_exc())
            self.failed = True
        self.out.put(("done", self.failed))

    def step_install(self):
        b = bundle_root()
        tree = b / "tree"
        if not (tree / "AntigravityPlugins.exe").exists():
            raise RuntimeError("安装包内部错误：缺少 tree/AntigravityPlugins.exe")
        self.say("安装目录: %s" % self.target)
        self.pct(1, "复制内置运行时（Node.js + Python，无需另外安装）")
        n = copy_tree(tree, self.target / "bin", lambda p: self.pct(1 + p // 3, "复制程序文件"))
        self.say("  已写入 %d 个文件" % n)

        node_src = b / "runtime" / "node.exe"
        if node_src.exists():
            self.pct(35, "复制便携版 Node.js")
            copy_tree(node_src.parent, self.target / "runtime", None)
            self.say("  node.exe %s -> runtime\\node.exe" % node_src)
        else:
            self.say("  [!] 安装包未内置 node.exe，将依赖系统 PATH")

        self.pct(40, "生成启动脚本")
        write_launchers(self.target)
        for name, _a, _p in LAUNCHERS:
            self.say("  %s" % name)

        self.pct(45, "创建快捷方式与卸载项")
        try:
            import aglaunch          # frozen module, same code the installed app runs
            ok, err = aglaunch.make_shortcuts(self.desktop, self.target)
            self.say("  快捷方式: %s%s" % ("已创建" if ok else "创建失败", "" if ok else " " + err))
            aglaunch.registry_write(self.target)
            self.say("  卸载项: 已写入 设置-应用")
        except BaseException as e:
            self.say("  [!] 快捷方式/注册表失败: %s" % e)

        install_guard_autostart(self.target, self.autostart)
        self.say("  开机守护: %s" % ("已启用（静默、无窗口）" if self.autostart else "未启用"))

        if self.deploy_now:
            self.pct(55, "部署插件并注入补丁")
            self.deploy()
        else:
            self.pct(100, "完成")

    def deploy(self):
        exe = str(self.target / "bin" / "AntigravityPlugins.exe")
        env = dict(os.environ)
        env["PYTHONIOENCODING"] = "utf-8"
        flags = 0x08000000 if os.name == "nt" else 0   # CREATE_NO_WINDOW: console app, hidden
        # --yes + closed stdin: the deployer must never block on a prompt nobody can answer
        p = subprocess.Popen([exe, "--deploy", "--yes"], cwd=str(self.target), env=env,
                             stdin=subprocess.DEVNULL,
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                             text=True, encoding="utf-8", errors="replace", bufsize=1,
                             creationflags=flags)
        for line in p.stdout:
            self.say(line.rstrip())
        rc = p.wait()
        self.pct(100, "部署结束")
        if rc != 0:
            self.say("[!] 部署返回码 %s，可稍后双击【一键全量部署】重试" % rc)
            self.failed = True


def gui_main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    silent = "--silent" in argv
    target = default_target()
    if "--target" in argv:
        target = Path(argv[argv.index("--target") + 1])

    if silent:
        class Printer:
            def put(self, item):
                kind, payload = item
                if kind == "log":
                    print(payload, flush=True)
                elif kind == "pct":
                    print("[%3d%%] %s" % payload, flush=True)

        w = Worker(target, True, True, "--no-deploy" not in argv, Printer())
        w.run()
        return 1 if w.failed else 0

    import tkinter as tk
    from tkinter import ttk, filedialog, messagebox

    root = tk.Tk()
    root.title("%s · 安装向导 %s" % (PRODUCT, VERSION))
    root.geometry("640x520")
    root.attributes("-topmost", True)

    head = tk.Label(root, text=PRODUCT, font=("Microsoft YaHei UI", 16, "bold"), anchor="w")
    head.pack(fill="x", padx=18, pady=(16, 0))
    tk.Label(root, text="深度中文汉化 · 上下文 Token 实时显示 · 用量智脑大盘\n"
                        "内置 Node.js 与 Python 运行时，无需另外安装任何环境",
             justify="left", fg="#555", anchor="w").pack(fill="x", padx=18, pady=(4, 10))

    row = tk.Frame(root); row.pack(fill="x", padx=18)
    tk.Label(row, text="安装到:").pack(side="left")
    ent = tk.Entry(row)
    ent.insert(0, str(target))
    ent.pack(side="left", fill="x", expand=True, padx=6)

    def browse():
        p = filedialog.askdirectory(initialdir=ent.get() or str(Path.home()))
        if p:
            ent.delete(0, "end"); ent.insert(0, p)

    tk.Button(row, text="浏览...", command=browse).pack(side="left")

    opts = tk.Frame(root); opts.pack(fill="x", padx=18, pady=(10, 6))
    v_desktop = tk.BooleanVar(value=True)
    v_guard = tk.BooleanVar(value=True)
    v_deploy = tk.BooleanVar(value=True)
    for text, var in (("创建桌面快捷方式（一键全量部署 / 恢复官方原版）", v_desktop),
                      ("启用开机静默守护（软件更新后自动重打补丁，无黑框）", v_guard),
                      ("安装完成后立即部署并注入补丁（推荐）", v_deploy)):
        tk.Checkbutton(opts, text=text, variable=var, anchor="w").pack(fill="x")

    bar = ttk.Progressbar(root, maximum=100)
    bar.pack(fill="x", padx=18, pady=(4, 6))
    status = tk.Label(root, text="待命", anchor="w", fg="#333")
    status.pack(fill="x", padx=18)

    txt = tk.Text(root, height=12, state="disabled", bg="#101418", fg="#d6e2ea",
                  font=("Consolas", 9))
    txt.pack(fill="both", expand=True, padx=18, pady=(2, 10))

    q = queue.Queue()
    btn = tk.Button(root, text="开始安装", width=16)
    btn.pack(pady=(0, 14))

    def drain():
        try:
            while True:
                kind, payload = q.get_nowait()
                if kind == "log":
                    txt.configure(state="normal")
                    txt.insert("end", payload + "\n")
                    txt.see("end")
                    txt.configure(state="disabled")
                elif kind == "pct":
                    value, label = payload
                    bar["value"] = value
                    status.configure(text=label or "处理中")
                elif kind == "done":
                    btn.configure(state="normal", text="完成，启动 Antigravity" if not payload else "重试")
                    status.configure(text="安装失败，请查看上方日志" if payload else "安装完成")
                    if not payload:
                        messagebox.showinfo(PRODUCT, "安装完成。\n\n开始菜单已创建：\n"
                                                    " · 一键全量部署\n · 插件管理中心\n · 智能启动与汉化\n"
                                                    " · 恢复官方原版\n\n如需卸载：设置 - 应用 - %s" % PRODUCT)
        except queue.Empty:
            pass
        root.after(120, drain)

    def start():
        t = Path(ent.get().strip() or str(default_target()))
        btn.configure(state="disabled", text="安装中...")
        w = Worker(t, v_desktop.get(), v_guard.get(), v_deploy.get(), q)
        threading.Thread(target=w.run, daemon=True).start()

    btn.configure(command=start)
    drain()
    root.mainloop()
    return 0


if __name__ == "__main__":
    sys.exit(gui_main())
